// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How other nodes communicate with this infrastructure pod
 */
export type ActionEndpoint = { 
/**
 * Port the sidecar/service listens on for action requests
 */
port: number, 
/**
 * HTTP path for action dispatch (e.g., "/action")
 */
path: string, };
