// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Edge = { id: string, source: string, target: string, sourceHandle: string | null, targetHandle: string | null, };
