// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupBoundaryRole } from "./GroupBoundaryRole";

/**
 * Marks a Passthrough node as a group boundary.
 */
export type GroupBoundary = { groupId: string, role: GroupBoundaryRole, };
