// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Role of a Passthrough node at a group boundary.
 */
export type GroupBoundaryRole = "In" | "Out";
