// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionEndpoint } from "./ActionEndpoint";
import type { KubeManifest } from "./KubeManifest";

/**
 * Infrastructure specification defined by the node itself.
 * This tells the platform exactly how to deploy and communicate with this node.
 * Node authors provide this,the platform is infrastructure-agnostic.
 */
export type InfrastructureSpec = { 
/**
 * Name of the sidecar (e.g., "postgres-database"). Image will be resolved to {REGISTRY}/sidecar-{name}:latest
 */
sidecarName: string, 
/**
 * Kubernetes manifests to apply (Deployment/StatefulSet, Service, PVC, etc.)
 */
manifests: Array<KubeManifest>, 
/**
 * How other nodes send actions to this infrastructure
 */
actionEndpoint: ActionEndpoint, };
