// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A Kubernetes resource manifest template.
 * The platform will inject namespace, instance ID, labels, etc.
 */
export type KubeManifest = { 
/**
 * Raw K8s manifest as JSON (Deployment, Service, PVC, StatefulSet, etc.)
 */
manifest: JsonValue, };
