// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a port interacts with the lane/stack system.
 * - Single: normal, one value per lane (default)
 * - Expand: this port carries a list that expands into N lanes downstream
 * - Gather: this port collects values from all N lanes into a single list
 */
export type LaneMode = "Single" | "Expand" | "Gather";
