// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * NodeType is now a simple String wrapper to allow dynamic node types.
 * New nodes can be added by dropping them in the nodes folder without
 * modifying this enum.
 */
export type NodeType = string;
