// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InfrastructureSpec } from "./InfrastructureSpec";
import type { TriggerCategory } from "./TriggerCategory";

/**
 * Feature flags for nodes - describes what capabilities a node has
 */
export type NodeFeatures = { 
/**
 * Node can act as a project trigger (has start/stop lifecycle)
 */
isTrigger: boolean, 
/**
 * Trigger category (only relevant if isTrigger is true)
 */
triggerCategory: TriggerCategory | null, 
/**
 * Trigger requires a running instance (false for Webhook/Manual which are event-driven)
 */
requiresRunningInstance: boolean, 
/**
 * Node allows adding custom input ports
 */
canAddInputPorts: boolean, 
/**
 * Node allows adding custom output ports
 */
canAddOutputPorts: boolean, 
/**
 * Node is an infrastructure node (long-running, provides actions to other nodes)
 */
isInfrastructure: boolean, 
/**
 * Infrastructure deployment specification (only for infrastructure nodes).
 * Defines the K8s manifests, readiness check, and action endpoint.
 * The node itself controls how it gets deployed.
 */
infrastructureSpec: InfrastructureSpec | null, 
/**
 * Sidecar exposes a /live endpoint with typed data items for real-time dashboard display.
 */
hasLiveData: boolean, 
/**
 * Node has a dynamic form schema. Ports are derived from config.fields at build time.
 * enrich.rs preserves these ports even though canAddInputPorts/canAddOutputPorts are false.
 */
hasFormSchema: boolean, 
/**
 * Groups of ports where at least one must be non-null for the node to execute.
 * If all ports in a group are null/missing, the node is skipped.
 * e.g. [["text", "media"]] = at least one of text/media must be non-null.
 */
oneOfRequired: Array<Array<string>>, };
