// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupBoundary } from "./GroupBoundary";
import type { JsonValue } from "./serde_json/JsonValue";
import type { NodeFeatures } from "./NodeFeatures";
import type { NodeType } from "./NodeType";
import type { PortDefinition } from "./PortDefinition";
import type { Position } from "./Position";

export type NodeDefinition = { id: string, nodeType: NodeType, label: string | null, config: JsonValue, position: Position, inputs: Array<PortDefinition>, outputs: Array<PortDefinition>, features: NodeFeatures, 
/**
 * Group IDs this node is nested inside, from outermost to innermost.
 * Empty for top-level nodes. E.g. ["outer", "outer.inner"] for a node in outer.inner.
 */
scope: Array<string>, 
/**
 * If this node is a Passthrough at a group boundary, which group and which side.
 */
groupBoundary: GroupBoundary | null, };
