// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaneMode } from "./LaneMode";
import type { WeftType } from "./WeftType";

export type PortDefinition = { name: string, portType: WeftType, required: boolean, description: string | null, laneMode: LaneMode, 
/**
 * Number of List[] levels to expand/gather. Default 1.
 * For `List[List[String]]` → `String`, this is 2 (peel two List layers).
 */
laneDepth: number, 
/**
 * Whether this port can be filled by a same-named config field on the
 * node (in addition to being wired by an edge). Defaults to true for
 * every port type except Media (Image/Audio/Video/Document and unions
 * thereof), TypeVar, and MustOverride, those are wired-only.
 * Catalog authors can opt out per port via PortDef::wired_only(...).
 * Edge wins over config when both are present.
 */
configurable: boolean, };
