// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Primitive } from "./Primitive";

/**
 * Recursive port type system.
 */
export type PortType = { "Primitive": Primitive } | { "List": PortType } | { "Dict": [PortType, PortType] } | { "Union": Array<PortType> } | { "TypeVar": string } | "MustOverride";
