// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrimitivePortType = "String" | "Number" | "Boolean" | "Dict" | "List" | "Image" | "Video" | "Audio" | "Document" | "Any";
