// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Primitive = "String" | "Number" | "Boolean" | "Null" | "Image" | "Video" | "Audio" | "Document";
