// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";
import type { NodeDefinition } from "./NodeDefinition";
import type { ProjectStatus } from "./ProjectStatus";

export type ProjectDefinition = { id: string, name: string, description: string | null, nodes: Array<NodeDefinition>, edges: Array<Edge>, status: ProjectStatus, createdAt: string, updatedAt: string, };
