// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionStatus } from "./ExecutionStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type ProjectExecution = { id: string, projectId: string, status: ExecutionStatus, startedAt: string, completedAt: string | null, currentNode: string | null, state: JsonValue, error: string | null, };
