// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Category of trigger - determines how the trigger operates
 */
export type TriggerCategory = "Webhook" | "Socket" | "Polling" | "Schedule" | "Local" | "Manual";
