// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeftPrimitive } from "./WeftPrimitive";

/**
 * Recursive port type system.
 */
export type WeftType = { "Primitive": WeftPrimitive } | { "List": WeftType } | { "Dict": [WeftType, WeftType] } | { "Union": Array<WeftType> } | "JsonDict" | { "TypeVar": string } | "MustOverride";
